"""Visualization helpers (Phase 12).

This subpackage provides read-only plotting utilities that consume the
output CSV generated by the runner and write PNGs under `output/plots/`.

The plotting functions make no changes to model logic or inputs.
"""

__all__ = [
    "plot_revenue_total_and_by_sector",
    "plot_revenue_by_material",
    "plot_leads_and_clients",
    "plot_order_basket_vs_delivery",
    "plot_capacity_utilization",
    "generate_all_plots_from_csv",
]
